###
### Bolt Forms
###

## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.
# NOTE: setting the debug on a specific form will override these global settings
# — specific for and to that form. It is considered best practice to use only
# this global setting.
debug:
    enabled: false
    address: johnathan@jpulos.com

## CSRF protection
#
# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

submit_an_idea:
  notification:
    enabled: true
    to_email: forms@missionaldigerati.info
    to_name: 'Missional Digerati'
    from_name: 'Zombies on Rails'
    from_email: zombie.on.rails@gmail.com
    subject: "[MD] Submit an Idea"
  feedback:
      success: Thank you for the great idea!
      error: There are errors in the form, please fix before trying to resubmit.
  fields:
    name:
      type: text
      options:
        required: true
        label: 'Your Name'
        attr:
          placeholder: 'Your name is...'
    email:
      type: email
      options:
        required: true
        label: 'Your Email'
        attr:
          placeholder: 'Your email address is...'
    phone:
      type: text
      options:
        required: false
        label: 'Your Phone Number'
        attr:
          placeholder: 'Your phone number is...'
    skype:
      type: text
      options:
        required: false
        label: 'Your Skype Handle'
        attr:
          placeholder: 'Your Skype handle is...'
    idea:
      type: textarea
      options:
        required: true
        label: 'Your Idea'
        attr:
          placeholder: 'Your idea is...'
    submit:
      type: submit
      options:
        label: Submit Your Idea
        attr:
          class: btn-submit btn

contact_us:
  notification:
    enabled: true
    to_email: forms@missionaldigerati.info
    to_name: 'Missional Digerati'
    from_name: 'Zombies on Rails'
    from_email: zombie.on.rails@gmail.com
    subject: "[MD] Contact Us"
  feedback:
      success: Thank you for your message!
      error: There are errors in the form, please fix before trying to resubmit.
  fields:
    name:
      type: text
      options:
        required: true
        label: 'Your Name'
        attr:
          placeholder: 'Your name is...'
    email:
      type: email
      options:
        required: true
        label: 'Your Email'
        attr:
          placeholder: 'Your email address is...'
    phone:
      type: text
      options:
        required: false
        label: 'Your Phone Number'
        attr:
          placeholder: 'Your phone number is...'
    skype:
      type: text
      options:
        required: false
        label: 'Your Skype Handle'
        attr:
          placeholder: 'Your Skype handle is...'
    message:
      type: textarea
      options:
        required: true
        label: 'Your Message'
        attr:
          placeholder: 'Your message is...'
    submit:
      type: submit
      options:
        label: Submit
        attr:
          class: btn-submit btn

join_volunteer:
  notification:
    enabled: true
    to_email: forms@missionaldigerati.info
    to_name: 'Missional Digerati'
    from_name: 'Zombies on Rails'
    from_email: zombie.on.rails@gmail.com
    subject: "[MD] Join/Volunteer"
  feedback:
      success: Thank you for your message!
      error: There are errors in the form, please fix before trying to resubmit.
  fields:
    type_of_service:
      type: choice
      options:
        required: true
        label: 'How Would You Like To Help?'
        choices: {'Micro-Volunteering Digerati': 'micro_volunteer', 'Full-Time Digerati': 'fulltime', 'Not Sure?!?': 'not_sure' }
    name:
      type: text
      options:
        required: true
        label: 'Your Name'
        attr:
          placeholder: 'Your name is...'
    email:
      type: email
      options:
        required: true
        label: 'Your Email'
        attr:
          placeholder: 'Your email address is...'
    phone:
      type: text
      options:
        required: false
        label: 'Your Phone Number'
        attr:
          placeholder: 'Your phone number is...'
    skype:
      type: text
      options:
        required: false
        label: 'Your Skype Handle'
        attr:
          placeholder: 'Your Skype handle is...'
    bio:
      type: textarea
      options:
        required: false
        label: 'Tell Us More About You!'
        attr:
          placeholder: 'You are...'
    skills:
      type: textarea
      options:
        required: false
        label: 'Tell Us How God Has Gifted You!'
        attr:
          placeholder: 'Your gifts are...'
    message:
      type: textarea
      options:
        required: false
        label: 'If You Would Like To Tell us More.'
        attr:
          placeholder: 'Your message is...'
    submit:
      type: submit
      options:
        label: Submit
        attr:
          class: btn-submit btn
