# This is the config file for the Simple Forms extension.

stylesheet: stylesheets/simpleforms.css
template: simpleforms/form.twig
mail_template: assets/simpleforms_mail.twig
message_ok: Thanks! Your message has been sent.
message_error: There was a problem with your submission!
message_technical: There were some technical difficulties, so your message was not sent. We apologize for the inconvenience.
button_text: Send
# Optional. Used only, when you have a file field.
# mime_types_message: "Not allowed file type. Allowed file types are:"

# ReCaptcha Config - Set these options to enable ReCaptcha spam protection.
# Generate your keys at https://www.google.com/recaptcha/admin/create
recaptcha_enabled: false
recaptcha_public_key: ''
recaptcha_private_key: ''
recaptcha_error_message: "The CAPTCHA wasn't entered correctly. Please try again."
recaptcha_theme: clean

# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

# Default fallback sender email
# this is required because Swiftmailer will reject the message without one
# please make this a sensible existing email address
from_email: johnathan@missionaldigerati.org
from_name: Johnathan Pulos

# global cc email address
# set this value to an email address that will receive a copy of every email from simpleforms
# recipient_cc_email: info@example.com
# recipient_cc_name: Info

# global bcc email address
# set this value to an email address that will receive a blind copy of every email from simpleforms
# recipient_bcc_email: info@example.com

# global testmode
# for development all email will be sent to this address
# all other recipient and cc addresses will be ignored
# remove or set 'testmode' to false for a production site
testmode : false
testmode_recipient: johnathan@jpulos.com

# from_email and from_name can be set for picky SMTP servers

# A simple contact form. Use as {{ simpleform('contact') }} in your templates.
submit_an_idea:
  recipient_email: forms@missionaldigerati.info
  recipient_name: 'Missional Digerati'
  mail_subject: "[MD] Submit an Idea"
  insert_into_table: form_submit_idea
  fields:
    name:
      label: 'Your Name'
      placeholder: 'Your name is...'
      type: text
      required: true
    email:
      type: email
      label: 'Your Email'
      placeholder: 'Your email address is...'
      required: true
    phone:
      type: text
      label: 'Your Phone Number'
      placeholder: 'Your phone number is...'
    skype:
      type: text
      label: 'Your Skype Handle'
      placeholder: 'Your Skype handle is...'
    idea:
      type: textarea
      label: 'Your Idea'
      placeholder: 'Your idea is...'
      required: true
  button_text: Submit Your Idea

# A simple contact form. Use as {{ simpleform('contact') }} in your templates.
contact_us:
  recipient_email: forms@missionaldigerati.info
  recipient_name: 'Missional Digerati'
  mail_subject: "[MD] Contact Us"
  insert_into_table: form_contact_us
  fields:
    name:
      label: 'Your Name'
      placeholder: 'Your name is...'
      type: text
      required: true
    email:
      type: email
      label: 'Your Email'
      placeholder: 'Your email address is...'
      required: true
    phone:
      type: text
      label: 'Your Phone Number'
      placeholder: 'Your phone number is...'
    skype:
      type: text
      label: 'Your Skype Handle'
      placeholder: 'Your Skype handle is...'
    message:
      type: textarea
      label: 'Your Message'
      placeholder: 'Your message is...'
      required: true
  button_text: Submit

join_volunteer:
  recipient_email: forms@missionaldigerati.info
  recipient_name: 'Missional Digerati'
  mail_subject: "[MD] Join/Volunteer"
  insert_into_table: form_join_us
  fields:
    type_of_service:
      type: choice
      label: 'How Would You Like To Help?'
      empty_value: Please Select One
      choices:
        micro_volunteer: 'Micro-Volunteering Digerati'
        fulltime: 'Full-Time Digerati'
        not_sure: 'Not Sure?!?'
      required: true
    name:
      label: 'Your Name'
      placeholder: 'Your name is...'
      type: text
      required: true
    email:
      type: email
      label: 'Your Email'
      placeholder: 'Your email address is...'
      required: true
    phone:
      type: text
      label: 'Your Phone Number'
      placeholder: 'Your phone number is...'
    skype:
      type: text
      label: 'Your Skype Handle'
      placeholder: 'Your Skype handle is...'
    bio:
      type: textarea
      label: 'Tell Us More About You!'
      placeholder: 'You are...'
    skills:
      type: textarea
      label: 'Tell Us How God Has Gifted You!'
      placeholder: 'Your gifts are...'
    message:
      type: textarea
      label: 'If You Would Like To Tell us More.'
      placeholder: 'Your message is...'
  button_text: Submit

host_a_class:
  recipient_email: forms@missionaldigerati.info
  recipient_name: 'Missional Digerati'
  mail_subject: "[MD] Host a Class"
  insert_into_table: form_host_class
  fields:
    curriculum:
      type: text
      label: 'Curriculum'
    name:
      label: 'Your Name'
      placeholder: 'Your name is...'
      type: text
      required: true
    organization_name:
      label: 'Your Organization/Church'
      placeholder: 'Your organization or church name is...'
      type: text
      required: true
    email:
      type: email
      label: 'Your Email'
      placeholder: 'Your email address is...'
      required: true
    phone:
      type: text
      label: 'Your Phone Number'
      placeholder: 'Your phone number is...'
    skype:
      type: text
      label: 'Your Skype Handle'
      placeholder: 'Your Skype handle is...'
    address:
      type: textarea
      label: 'Your Address'
      placeholder: 'Your address is...'
    preferences:
      type: textarea
      label: 'When Would You Prefer to Have the Class?'
      placeholder: 'You prefer to hold the class on...'
    message:
      type: textarea
      label: 'Do You Want to Tell us Anything Else?'
      placeholder: 'Tell us more...'
    adequate_space:
      type: choice
      label: 'Do you have adequate space to host the class?'
      empty_value: Please Select One
      choices: 
        yes: Yes
        no: No
      required: true
    wifi_access:
      type: choice
      label: 'Do you have accessible WiFi for all the students?'
      empty_value: Please Select One
      choices: 
        yes: Yes
        no: No
      required: true
    share_ministry:
      type: choice
      label: 'Can we share the vision of our ministry during the last 15 minutes of class?'
      empty_value: Please Select One
      choices: 
        yes: Yes
        no: No
      required: true
    subsidize_trip:
      type: choice
      label: 'Are you willing to subsidize transportation and housing costs for 2 adults?'
      empty_value: Please Select One
      choices: 
        yes: Yes
        no: No
      required: true
      postfix: '<em>Cost only needs to be subsidized outside of Southern California.</em>'
    private:
      type: choice
      label: 'Are you OK with others outside your oganization to join this class?'
      empty_value: Please Select One
      choices: 
        yes: Yes
        no: No
      required: true
    statement_of_faith:
      type: checkbox
      label: 'Do you agree with our Statement of Faith?'
      postfix: '<a href="/about-us/statement-of-faith" target="_blank">Read Our Statement of Faith</a>'
      required: true

register_for_faith_and_tech:
  recipient_email: forms@missionaldigerati.info
  recipient_name: 'Missional Digerati'
  mail_subject: "[MD] Register for Faith & Tech Class"
  message_ok: "Thank You!  You have been registered for the class."
  insert_into_table: form_register_faith_tech
  fields:
    class:
      type: text
      label: 'Class'
    class_id:
      type: hidden
    name:
      label: 'Your Name'
      placeholder: 'Your name is...'
      type: text
      required: true
    email:
      type: email
      label: 'Your Email'
      placeholder: 'Your email address is...'
      required: true
    phone:
      type: text
      label: 'Your Phone Number'
      placeholder: 'Your phone number is...'
    spouse:
      type: choice
      label: 'Will a spouse be joining you?'
      empty_value: Please Select One
      choices:
        yes: Yes
        no: No
      required: true
    spouse_name:
      label: "Your Spouse's Name"
      placeholder: "Your spouse's name is..."
      type: text
    experience_computers:
      type: choice
      label: 'How would you rate your experience with computers?'
      empty_value: Please Select One
      choices:
        novice: 'Novice'
        low: 'Low Experience'
        moderate: 'Moderate Experience'
        experienced: 'Experienced'
      required: true
    experience_smart_phones:
      type: choice
      label: 'How would you rate your experience with smart phones?'
      empty_value: Please Select One
      choices: 
        novice: 'Novice'
        low: 'Low Experience'
        moderate: 'Moderate Experience'
        experienced: 'Experienced'
      required: true
    spouse_experience_computers:
      type: choice
      label: "How would you rate your spouse's experience with computers?"
      empty_value: Please Select One
      choices: 
        novice: 'Novice'
        low: 'Low Experience'
        moderate: 'Moderate Experience'
        experienced: 'Experienced'
    spouse_experience_smart_phones:
      type: choice
      label: "How would you rate your spouse's experience with smart phones?"
      empty_value: Please Select One
      choices:
        novice: 'Novice'
        low: 'Low Experience'
        moderate: 'Moderate Experience'
        experienced: 'Experienced'
    reason:
      type: textarea
      label: 'Why are you taking this class?'
      placeholder: 'Your reason here...'
  button_text: Register

register_for_digerati_101:
  recipient_email: forms@missionaldigerati.info
  recipient_name: 'Missional Digerati'
  mail_subject: "[MD] Register for Digerati 101 Class"
  message_ok: "Thank You!  You have been registered for the class."
  insert_into_table: form_register_digerati_101
  fields:
    class:
      type: text
      label: 'Class'
    class_id:
      type: hidden
    name:
      label: 'Your Name'
      placeholder: 'Your name is...'
      type: text
      required: true
    ministry:
      label: 'Your Ministry'
      placeholder: 'Your ministry is...'
      type: text
      required: true
      postfix: '<em>In order to take this class, you must be currently serving in a qualified nonprofit Evangelical Protestant mission agency.</em>'
    email:
      type: email
      label: 'Your Email'
      placeholder: 'Your email address is...'
      required: true
    phone:
      type: text
      label: 'Your Phone Number'
      placeholder: 'Your phone number is...'
    experience_programming:
      type: choice
      label: 'How would you rate your experience with programming?'
      empty_value: Please Select One
      choices:
        novice: 'Novice'
        low: 'Low Experience'
        moderate: 'Moderate Experience'
        experienced: 'Experienced'
      required: true
    programming_languages:
      type: textarea
      label: 'Programming Languages You Know?'
      placeholder: 'PHP, CSS, HTML ...'
    reason:
      type: textarea
      label: 'Why are you taking this class?'
      placeholder: 'Your reason here...'
  button_text: Register
# Landing Page Forms
#
digital_quiet_time_landing:
  recipient_email: forms@missionaldigerati.info
  recipient_name: 'Missional Digerati'
  mail_subject: "[MD] Host a Digital Quiet Time"
  # insert_into_table: form_dq_landing
  fields:
    name:
      label: 'Your Name'
      placeholder: 'Your name is...'
      type: text
      required: true
    organization_name:
      label: 'Your Organization/Church'
      placeholder: 'Your organization or church name is...'
      type: text
      required: true
    email:
      type: email
      label: 'Your Email'
      placeholder: 'Your email address is...'
      required: true
    requirements:
      type: checkbox
      required: true
      label: 'Yes, my church meets the requirements?<br><a href="#requirements-modal" data-toggle="modal" class="learn_more requirements-modal-link">What Requirements?</a>'
    statement_of_faith:
      type: checkbox
      label: 'Yes, my church agrees with the Statement of Faith?<br><a href="#statement-faith-modal" data-toggle="modal" class="learn_more requirements-modal-link">Read Our Statement of Faith</a>'
      required: true
  button_text: Sign Me Up!
