# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    title: Visit the Home Page
    path:  /
    class: home
  - label: About Us
    title: Learn More About Us
    path:  /about-us
    class: about
  - label: Projects
    title: Discover Some of Our Projects
    path:  /projects
    class: projects
  - label: Training
    title: Check Out Our Classes
    path:  /training
    class: training
    submenu:
      - label: Digerati 101
        title: Learn How to Code
        path:  /training/digerati-101
        class: training-digerati-101
      - label: 'Faith & Tech'
        title: Learn More About Technology
        path:  /training/faith-and-tech
        class: training-faith-and-tech
  - label: Submit an Idea
    title: Got a Great Idea
    path:  /submit-an-idea
    class: submit-an-idea
  - label: Code
    title: Checkout Our Code
    link:  https://github.com/MissionalDigerati
    class: code-repo
  - label: Contact Us
    title: Get in Touch
    path:  /contact-us
    class: contact-us
footer:
  - label: Home
    title: Visit the Home Page
    path:  /
    class: home
  - label: About Us
    title: Learn More About Us
    path:  /about-us
    class: about
  - label: Projects
    title: Discover Some of Our Projects
    path:  /projects
    class: projects
  - label: Training
    title: Check Out Our Classes
    path:  /training
    class: training
  - label: Submit an Idea
    title: Got a Great Idea
    path:  /submit-an-idea
    class: submit-an-idea
  - label: Code
    title: Checkout Our Code
    link:  https://github.com/MissionalDigerati
    class: code-repo
  - label: Contact Us
    title: Get in Touch
    path:  /contact-us
    class: contact-us