# This file defines user-definable routes for the frontend of your Bolt website.
# Check below for examples, or read the documentation at
# https://docs.bolt.cm/configuration/routing

# ------------------------------------------------------------------------------
# Place your own routes here, that have a HIGHER priority than the default routes.

about_us_pages:
  path: /about-us/{slug}
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page

about_us:
  path: /about-us
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page
    slug: our-ministry

projects:
  path: /projects
  defaults:
    _controller: controller.frontend:listing
    contenttypeslug: projects

training_pages:
  path: /training/{slug}
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page

participate:
  path: /participate
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page
    slug: donate

participate_pages:
  path: /participate/{slug}
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page

root:
  path: /
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page
    slug: welcome

pagebinding:
  path: /{slug}
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page

# ------------------------------------------------------------------------------
# These are the routes defining the default behaviour of Bolt's frontend.
# Changing these might give unexpected results or even break your website. If
# possible, only add NEW routes above or below these.

homepage:
    path: /
    defaults:
        _controller: controller.frontend:homepage

search:
    path: /search
    defaults:
        _controller: controller.frontend:search

preview:
    path: /preview/{contenttypeslug}
    defaults:
        _controller: controller.frontend:preview
    requirements:
        contenttypeslug: controller.requirement:anyContentType
    methods: [POST]

contentlink:
    path: /{contenttypeslug}/{slug}
    defaults:
        _controller: controller.frontend:record
    requirements:
        contenttypeslug: controller.requirement:anyContentType

taxonomylink:
    path: /{taxonomytype}/{slug}
    defaults:
        _controller: controller.frontend:taxonomy
    requirements:
        taxonomytype: controller.requirement:anyTaxonomyType

contentlisting:
    path: /{contenttypeslug}
    defaults:
        _controller: controller.frontend:listing
    requirements:
        contenttypeslug: controller.requirement:pluralContentTypes
